services:
  tech_service_db_host:
    container_name: tech_service_db
    hostname: tech_service_db_host
    image: postgres:15
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    command: postgres -p 5433
    ports:
      - "5432:5433"  # Проброс порта 5432 хоста в порт 5433 контейнера
    environment:
      POSTGRES_LISTEN_ADDRESSES: '*'
      POSTGRES_HOST_AUTH_METHOD: trust


  tech_service_app:
    container_name: tech_service
    image: tech_service_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "5952:8000"
    depends_on:
      - tech_service_db_host

volumes:
  app_pg_data:
  app_pg_data_backups:
