"""refactor comments

Revision ID: 89c6279f97f4
Revises: 92f02acb1e5a
Create Date: 2025-01-30 17:27:49.079145

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89c6279f97f4"
down_revision = "92f02acb1e5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auth_refresh_token_user_id_fkey", "auth_refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_executor_additional_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint("company_user_id_fkey", "company", type_="foreignkey")
    op.drop_constraint(
        "company_executor_default_id_fkey", "company", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_contacts_company_id_fkey", "company_contacts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.add_column(
        "executor_comments", sa.Column("service_id", sa.UUID(), nullable=False)
    )
    op.alter_column(
        "executor_comments", "executor_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "executor_comments", "comment", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_index(
        op.f("ix_executor_comments_executor_id"),
        "executor_comments",
        ["executor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executor_comments_service_id"),
        "executor_comments",
        ["service_id"],
        unique=False,
    )
    op.drop_constraint(
        "executor_comments_executor_id_fkey", "executor_comments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "executor_comments",
        "services",
        ["service_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "executor_comments",
        "users",
        ["executor_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "executor_default_customer_id_fkey", "executor_default", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("media_files_service_id_fkey", "media_files", type_="foreignkey")
    op.create_foreign_key(
        None,
        "media_files",
        "services",
        ["service_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "services_executor_default_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint("services_customer_id_fkey", "services", type_="foreignkey")
    op.drop_constraint("services_company_id_fkey", "services", type_="foreignkey")
    op.drop_constraint(
        "services_executor_additional_id_fkey", "services", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "services_executor_additional_id_fkey",
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.create_foreign_key(
        "services_company_id_fkey", "services", "company", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        "services_customer_id_fkey", "services", "users", ["customer_id"], ["id"]
    )
    op.create_foreign_key(
        "services_executor_default_id_fkey",
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.drop_constraint(None, "media_files", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "media_files_service_id_fkey", "media_files", "services", ["service_id"], ["id"]
    )
    op.drop_constraint(None, "executor_default", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "executor_default_customer_id_fkey",
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
    )
    op.drop_constraint(None, "executor_comments", type_="foreignkey")
    op.drop_constraint(None, "executor_comments", type_="foreignkey")
    op.create_foreign_key(
        "executor_comments_executor_id_fkey",
        "executor_comments",
        "users",
        ["executor_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_executor_comments_service_id"), table_name="executor_comments"
    )
    op.drop_index(
        op.f("ix_executor_comments_executor_id"), table_name="executor_comments"
    )
    op.alter_column(
        "executor_comments", "comment", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "executor_comments", "executor_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("executor_comments", "service_id")
    op.drop_constraint(None, "company_contacts", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_contacts_company_id_fkey",
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_executor_default_id_fkey",
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_user_id_fkey", "company", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "company_executor_additional_id_fkey",
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.drop_constraint(None, "auth_refresh_token", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "auth_refresh_token_user_id_fkey",
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
