"""Create tables

Revision ID: 6a1ea56b96c9
Revises: 
Create Date: 2025-04-11 16:20:53.974997

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a1ea56b96c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_customer", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_executor", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "role",
            sa.Enum("UNBIND", "ADMIN", "CUSTOMER", "EXECUTOR", name="roles"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_users_id"), "users", ["id"], unique=True, schema="public"
    )
    op.create_index(
        op.f("ix_public_users_username"),
        "users",
        ["username"],
        unique=True,
        schema="public",
    )
    op.create_table(
        "auth_refresh_token",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        schema="public",
    )
    op.create_table(
        "company",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("executor_default_id", sa.Integer(), nullable=True),
        sa.Column("executor_additional_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("opening_time", sa.String(), nullable=True),
        sa.Column("closing_time", sa.String(), nullable=True),
        sa.Column(
            "only_weekdays", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["executor_additional_id"],
            ["public.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["executor_default_id"],
            ["public.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_company_id"), "company", ["id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_company_user_id"),
        "company",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "executor_default",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("customer_id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_executor_default_customer_id"),
        "executor_default",
        ["customer_id"],
        unique=True,
        schema="public",
    )
    op.create_table(
        "company_contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("person", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["public.company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_company_contacts_company_id"),
        "company_contacts",
        ["company_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_company_contacts_id"),
        "company_contacts",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "services",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("executor_default_id", sa.Integer(), nullable=True),
        sa.Column("executor_additional_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "material_availability",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("emergency", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "custom_position", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("viewed_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "viewed_customer", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "viewed_executor_default",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "viewed_executor_additional",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deadline_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WORKING",
                "VERIFYING",
                "CLOSED",
                "CUSTOM",
                "REFUSED",
                name="servicestatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["public.company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["public.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["executor_additional_id"],
            ["public.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["executor_default_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_services_company_id"),
        "services",
        ["company_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_services_customer_id"),
        "services",
        ["customer_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_services_executor_additional_id"),
        "services",
        ["executor_additional_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_services_executor_default_id"),
        "services",
        ["executor_default_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_services_id"), "services", ["id"], unique=False, schema="public"
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_role",
            sa.Enum("UNBIND", "ADMIN", "CUSTOMER", "EXECUTOR", name="roles"),
            nullable=True,
        ),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("user_phone", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["public.services.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=True)
    op.create_index(
        op.f("ix_comments_service_id"), "comments", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_comments_user_name"), "comments", ["user_name"], unique=False
    )
    op.create_index(
        op.f("ix_comments_user_phone"), "comments", ["user_phone"], unique=False
    )
    op.create_index(
        op.f("ix_comments_user_role"), "comments", ["user_role"], unique=False
    )
    op.create_table(
        "media_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column(
            "file_type", sa.Enum("IMAGE", "VIDEO", name="filetypes"), nullable=False
        ),
        sa.Column(
            "owner_type",
            sa.Enum("CUSTOMER", "EXECUTOR", name="ownertypes"),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["public.services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_media_files_id"),
        "media_files",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_media_files_service_id"),
        "media_files",
        ["service_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_media_files_service_id"),
        table_name="media_files",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_media_files_id"), table_name="media_files", schema="public"
    )
    op.drop_table("media_files", schema="public")
    op.drop_index(op.f("ix_comments_user_role"), table_name="comments")
    op.drop_index(op.f("ix_comments_user_phone"), table_name="comments")
    op.drop_index(op.f("ix_comments_user_name"), table_name="comments")
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_service_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_public_services_id"), table_name="services", schema="public")
    op.drop_index(
        op.f("ix_public_services_executor_default_id"),
        table_name="services",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_services_executor_additional_id"),
        table_name="services",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_services_customer_id"), table_name="services", schema="public"
    )
    op.drop_index(
        op.f("ix_public_services_company_id"), table_name="services", schema="public"
    )
    op.drop_table("services", schema="public")
    op.drop_index(
        op.f("ix_public_company_contacts_id"),
        table_name="company_contacts",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_company_contacts_company_id"),
        table_name="company_contacts",
        schema="public",
    )
    op.drop_table("company_contacts", schema="public")
    op.drop_index(
        op.f("ix_public_executor_default_customer_id"),
        table_name="executor_default",
        schema="public",
    )
    op.drop_table("executor_default", schema="public")
    op.drop_index(
        op.f("ix_public_company_user_id"), table_name="company", schema="public"
    )
    op.drop_index(op.f("ix_public_company_id"), table_name="company", schema="public")
    op.drop_table("company", schema="public")
    op.drop_table("auth_refresh_token", schema="public")
    op.drop_index(op.f("ix_public_users_username"), table_name="users", schema="public")
    op.drop_index(op.f("ix_public_users_id"), table_name="users", schema="public")
    op.drop_table("users", schema="public")
    # ### end Alembic commands ###
