"""feat: update comment model/2

Revision ID: 93c63b2e55e3
Revises: 34051ed2af3a
Create Date: 2025-02-23 18:44:09.250296

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93c63b2e55e3"
down_revision = "34051ed2af3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auth_refresh_token_user_id_fkey", "auth_refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_service_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None,
        "comments",
        "services",
        ["service_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "comments",
        "users",
        ["user_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "company_executor_additional_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint(
        "company_executor_default_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint("company_user_id_fkey", "company", type_="foreignkey")
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_contacts_company_id_fkey", "company_contacts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "executor_default_customer_id_fkey", "executor_default", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("media_files_service_id_fkey", "media_files", type_="foreignkey")
    op.create_foreign_key(
        None,
        "media_files",
        "services",
        ["service_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "services_executor_default_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint("services_customer_id_fkey", "services", type_="foreignkey")
    op.drop_constraint("services_company_id_fkey", "services", type_="foreignkey")
    op.drop_constraint(
        "services_executor_additional_id_fkey", "services", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "services_executor_additional_id_fkey",
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.create_foreign_key(
        "services_company_id_fkey", "services", "company", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        "services_customer_id_fkey", "services", "users", ["customer_id"], ["id"]
    )
    op.create_foreign_key(
        "services_executor_default_id_fkey",
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.drop_constraint(None, "media_files", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "media_files_service_id_fkey", "media_files", "services", ["service_id"], ["id"]
    )
    op.drop_constraint(None, "executor_default", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "executor_default_customer_id_fkey",
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
    )
    op.drop_constraint(None, "company_contacts", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_contacts_company_id_fkey",
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_user_id_fkey", "company", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "company_executor_default_id_fkey",
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_executor_additional_id_fkey",
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_service_id_fkey",
        "comments",
        "services",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_user_id_fkey",
        "comments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "auth_refresh_token", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "auth_refresh_token_user_id_fkey",
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
