"""refactor all comments

Revision ID: 7916d776f79d
Revises: 6268d8e2fd43
Create Date: 2025-01-30 21:49:03.606781

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7916d776f79d"
down_revision = "6268d8e2fd43"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auth_refresh_token_user_id_fkey", "auth_refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.add_column("comments", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_index("ix_comments_executor_id", table_name="comments")
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    op.drop_constraint("comments_executor_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_service_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None,
        "comments",
        "users",
        ["user_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "comments",
        "services",
        ["service_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_column("comments", "executor_id")
    op.drop_constraint(
        "company_executor_additional_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint("company_user_id_fkey", "company", type_="foreignkey")
    op.drop_constraint(
        "company_executor_default_id_fkey", "company", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_contacts_company_id_fkey", "company_contacts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "executor_default_customer_id_fkey", "executor_default", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("media_files_service_id_fkey", "media_files", type_="foreignkey")
    op.create_foreign_key(
        None,
        "media_files",
        "services",
        ["service_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "services_executor_additional_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint(
        "services_executor_default_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint("services_company_id_fkey", "services", type_="foreignkey")
    op.drop_constraint("services_customer_id_fkey", "services", type_="foreignkey")
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "services_customer_id_fkey", "services", "users", ["customer_id"], ["id"]
    )
    op.create_foreign_key(
        "services_company_id_fkey", "services", "company", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        "services_executor_default_id_fkey",
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "services_executor_additional_id_fkey",
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.drop_constraint(None, "media_files", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "media_files_service_id_fkey", "media_files", "services", ["service_id"], ["id"]
    )
    op.drop_constraint(None, "executor_default", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "executor_default_customer_id_fkey",
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
    )
    op.drop_constraint(None, "company_contacts", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_contacts_company_id_fkey",
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_executor_default_id_fkey",
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_user_id_fkey", "company", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "company_executor_additional_id_fkey",
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.add_column(
        "comments",
        sa.Column("executor_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_service_id_fkey",
        "comments",
        "services",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_executor_id_fkey",
        "comments",
        "users",
        ["executor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.create_index(
        "ix_comments_executor_id", "comments", ["executor_id"], unique=False
    )
    op.drop_column("comments", "user_id")
    op.drop_constraint(None, "auth_refresh_token", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "auth_refresh_token_user_id_fkey",
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
