"""add_password_resset_atemp_table

Revision ID: 019fed43b992
Revises: 44af2c687fe3
Create Date: 2025-12-07 17:57:30.943045

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "019fed43b992"
down_revision = "44af2c687fe3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_password_reset_attempt",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("failed_attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("email"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_auth_password_reset_attempt_last_attempt_at"),
        "auth_password_reset_attempt",
        ["last_attempt_at"],
        unique=False,
        schema="public",
    )
    op.drop_constraint(
        "auth_password_reset_token_user_id_fkey",
        "auth_password_reset_token",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "auth_password_reset_token",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "auth_refresh_token_user_id_fkey", "auth_refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("comments_user_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_service_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None,
        "comments",
        "services",
        ["service_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "comments",
        "users",
        ["user_id"],
        ["id"],
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint("company_user_id_fkey", "company", type_="foreignkey")
    op.drop_constraint(
        "company_executor_additional_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint(
        "company_executor_default_id_fkey", "company", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_contacts_company_id_fkey", "company_contacts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "executor_default_customer_id_fkey", "executor_default", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("media_files_service_id_fkey", "media_files", type_="foreignkey")
    op.create_foreign_key(
        None,
        "media_files",
        "services",
        ["service_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "services_executor_additional_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint(
        "services_executor_default_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint("services_company_id_fkey", "services", type_="foreignkey")
    op.drop_constraint("services_customer_id_fkey", "services", type_="foreignkey")
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "services_customer_id_fkey", "services", "users", ["customer_id"], ["id"]
    )
    op.create_foreign_key(
        "services_company_id_fkey", "services", "company", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        "services_executor_default_id_fkey",
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "services_executor_additional_id_fkey",
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.drop_constraint(None, "media_files", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "media_files_service_id_fkey", "media_files", "services", ["service_id"], ["id"]
    )
    op.drop_constraint(None, "executor_default", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "executor_default_customer_id_fkey",
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
    )
    op.drop_constraint(None, "company_contacts", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_contacts_company_id_fkey",
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_executor_default_id_fkey",
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_executor_additional_id_fkey",
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_user_id_fkey", "company", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_service_id_fkey",
        "comments",
        "services",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "comments_user_id_fkey",
        "comments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "auth_refresh_token", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "auth_refresh_token_user_id_fkey",
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "auth_password_reset_token", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        "auth_password_reset_token_user_id_fkey",
        "auth_password_reset_token",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_public_auth_password_reset_attempt_last_attempt_at"),
        table_name="auth_password_reset_attempt",
        schema="public",
    )
    op.drop_table("auth_password_reset_attempt", schema="public")
    # ### end Alembic commands ###
