"""add executor_comments

Revision ID: 92f02acb1e5a
Revises: 383e3cf72c3f
Create Date: 2025-01-30 17:05:28.245282

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92f02acb1e5a"
down_revision = "383e3cf72c3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executor_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("executor_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["executor_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_executor_comments_id"), "executor_comments", ["id"], unique=True
    )
    op.drop_constraint(
        "auth_refresh_token_user_id_fkey", "auth_refresh_token", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_executor_additional_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint(
        "company_executor_default_id_fkey", "company", type_="foreignkey"
    )
    op.drop_constraint("company_user_id_fkey", "company", type_="foreignkey")
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "company",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "company_contacts_company_id_fkey", "company_contacts", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint(
        "executor_default_customer_id_fkey", "executor_default", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("media_files_service_id_fkey", "media_files", type_="foreignkey")
    op.create_foreign_key(
        None,
        "media_files",
        "services",
        ["service_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.add_column("services", sa.Column("comment_customer", sa.String(), nullable=True))
    op.drop_constraint(
        "services_executor_default_id_fkey", "services", type_="foreignkey"
    )
    op.drop_constraint("services_company_id_fkey", "services", type_="foreignkey")
    op.drop_constraint("services_customer_id_fkey", "services", type_="foreignkey")
    op.drop_constraint(
        "services_executor_additional_id_fkey", "services", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["customer_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "company",
        ["company_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.drop_constraint(None, "services", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "services_executor_additional_id_fkey",
        "services",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.create_foreign_key(
        "services_customer_id_fkey", "services", "users", ["customer_id"], ["id"]
    )
    op.create_foreign_key(
        "services_company_id_fkey", "services", "company", ["company_id"], ["id"]
    )
    op.create_foreign_key(
        "services_executor_default_id_fkey",
        "services",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.drop_column("services", "comment_customer")
    op.drop_constraint(None, "media_files", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "media_files_service_id_fkey", "media_files", "services", ["service_id"], ["id"]
    )
    op.drop_constraint(None, "executor_default", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "executor_default_customer_id_fkey",
        "executor_default",
        "users",
        ["customer_id"],
        ["id"],
    )
    op.drop_constraint(None, "company_contacts", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_contacts_company_id_fkey",
        "company_contacts",
        "company",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.drop_constraint(None, "company", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "company_user_id_fkey", "company", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "company_executor_default_id_fkey",
        "company",
        "users",
        ["executor_default_id"],
        ["id"],
    )
    op.create_foreign_key(
        "company_executor_additional_id_fkey",
        "company",
        "users",
        ["executor_additional_id"],
        ["id"],
    )
    op.drop_constraint(None, "auth_refresh_token", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "auth_refresh_token_user_id_fkey",
        "auth_refresh_token",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_executor_comments_id"), table_name="executor_comments")
    op.drop_table("executor_comments")
    # ### end Alembic commands ###
